version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${USER:-sail}
        uid: ${UID:-1000}
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - REDIS_HOST=redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: gapura_training
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_USER: gapura_user
      MYSQL_PASSWORD: gapura_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql_data:
